### ISSUE TITLE
laravel-cloudinary

### ISSUE THREAD

**Issue by IanEdington** [askaoru/hyperion#3]
Hey @askaoru your cloudinary integration disapeared. Could you publish the source so I can take over development of it?

I would give you 🌟 🌟 🌟

**Comment by askaoru** [comment]
Hello @IanEdington . Unfortunately I did not had any backup for that package anymore. 
It was abandoned over 2 years ago and I never felt like it was good enough. I would suggest https://github.com/jrm2k6/cloudder to be used instead.

**Comment by IanEdington** [comment]
@askaoru Thanks anyways 😄
